# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'arayuz.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(750, 700)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(25, 25, 81, 16))
        self.label.setObjectName("label")
        self.arayuz_metin = QtWidgets.QTextEdit(Form)
        self.arayuz_metin.setGeometry(QtCore.QRect(125, 25, 600, 300))
        self.arayuz_metin.setObjectName("arayuz_metin")
        self.ozetle_btn = QtWidgets.QPushButton(Form)
        self.ozetle_btn.setGeometry(QtCore.QRect(550, 360, 100, 25))
        self.ozetle_btn.setObjectName("ozetle_btn")
        self.arayuz_ozet_metin = QtWidgets.QTextEdit(Form)
        self.arayuz_ozet_metin.setGeometry(QtCore.QRect(125, 420, 600, 200))
        self.arayuz_ozet_metin.setObjectName("arayuz_ozet_metin")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 420, 121, 16))
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(350, 360, 100, 25))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(125, 330, 200, 15))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(125, 625, 200, 15))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.comboBox_2 = QtWidgets.QComboBox(Form)
        self.comboBox_2.setGeometry(QtCore.QRect(150, 360, 100, 25))
        self.comboBox_2.setEditable(False)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(50, 360, 100, 25))
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Metin Özetleme Arayüzü"))
        self.label.setText(_translate("Form", "Metni giriniz:"))
        self.ozetle_btn.setText(_translate("Form", "Metni Özetle"))
        self.label_3.setText(_translate("Form", "Girilen Metnin Özeti:"))
        self.comboBox.setCurrentText(_translate("Form", "Metin Özeti Dili"))
        self.comboBox.setItemText(0, _translate("Form", "Metin Özeti Dili"))
        self.comboBox.setItemText(1, _translate("Form", "Türkçe"))
        self.comboBox.setItemText(2, _translate("Form", "İngilizce"))
        self.comboBox_2.setCurrentText(_translate("Form", "50"))
        self.comboBox_2.setItemText(0, _translate("Form", "10"))
        self.comboBox_2.setItemText(1, _translate("Form", "20"))
        self.comboBox_2.setItemText(2, _translate("Form", "30"))
        self.comboBox_2.setItemText(3, _translate("Form", "40"))
        self.comboBox_2.setItemText(4, _translate("Form", "50"))
        self.comboBox_2.setItemText(5, _translate("Form", "60"))
        self.comboBox_2.setItemText(6, _translate("Form", "70"))
        self.comboBox_2.setItemText(7, _translate("Form", "80"))
        self.comboBox_2.setItemText(8, _translate("Form", "90"))
        self.label_5.setText(_translate("Form", "Özet Oranı (%)"))
